services:
  postgresdb:
    container_name: postgresdb
    image: postgres:16-bullseye
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - back-tier
    env_file:
      - ./backend/.env
    restart: on-failure:3

  api:
    container_name: backend
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend/:/usr/src/app/backend/
    networks:
      - front-tier
      - back-tier
    depends_on:
      - postgresdb
    env_file:
      - ./backend/.env
    restart: always

  # ui:
  #   container_name: frontend
  #   build: ./frontend
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - backend
  #   networks:
  #     - front-tier
  #   depends_on:
  #     - backend
  #   env_file:
  #     - ./frontend/.env

volumes:
  postgres_data:

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}


    # environment:
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_DB=${POSTGRES_DB}
