include:
  - db.yaml

services:
  api:
    container_name: backend
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend/:/usr/src/app/backend/
    networks:
      - front-tier
      - back-tier
    depends_on:
      - postgresdb
    env_file:
      - ./backend/.env
    restart: always

  ui:
    container_name: frontend
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - api
    volumes:
      - ./frontend/:/usr/src/app/frontend/
    networks:
      - front-tier
    env_file:
      - ./frontend/.env
    restart: on-failure:3

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}


    # environment:
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_DB=${POSTGRES_DB}
