services:
  postgresdb:
    container_name: postgresdb
    image: postgres:16-bullseye
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - back-tier
    env_file:
      - ./backend/.env
    restart: on-failure:3

networks:
  back-tier: {}

volumes:
  postgres_data:
