# Generated by Django 4.2 on 2024-08-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='<function file_upload_path at 0x7d4db25a1f30>'),
        ),
    ]
